// Delete Account
export const GET_DELETE_ACCOUNT = 'GET_DELETE_ACCOUNT'
export const SET_DELETE_ACCOUNT = 'SET_DELETE_ACCOUNT'

// Settings
export const GET_SPLASH = 'GET_SPLASH';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_REFRESHING = 'SET_IS_REFRESHING';
export const UPDATE_CALL_STATUS = 'UPDATE_CALL_STATUS';
export const UPDATE_CHAT_STATUS = 'UPDATE_CHAT_STATUS';
export const UPDATE_VIDEO_CALL_STATUS = 'UPDATE_VIDEO_CALL_STATUS'
export const SET_IMAGE_PICKER_VISIBLE = 'SET_IMAGE_PICKER_VISIBLE'
export const ON_NEXT_ONLINE = 'ON_NEXT_ONLINE'

//Auth
export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGOUT = 'ON_LOGOUT';
export const ON_APPLY_AS_AN_ASTROLOGER = 'ON_APPLY_AS_AN_ASTROLOGER';

//Provider
export const GET_PROVIDER_DATA = 'GET_PROVIDER_DATA';
export const SET_PROVIDER_DATA = 'SET_PROVIDER_DATA';
export const ON_REFERESH_HOME_SCREEN = 'ON_REFERESH_HOME_SCREEN';
export const GET_FOLLOWERS = 'GET_FOLLOWERS'
export const SET_FOLLOWERS = 'SET_FOLLOWERS'
export const GET_ASTROLOGER_REVIEW_DATA = 'GET_ASTROLOGER_REVIEW_DATA'
export const SET_ASTROLOGER_REVIEW_DATA = 'SET_ASTROLOGER_REVIEW_DATA'
export const GET_ALL_ANOUNCEMENT = 'GET_ALL_ANOUNCEMENT'
export const SET_ALL_ANOUNCEMENT = 'SET_ALL_ANOUNCEMENT'
export const ON_READ_ANOUNCEMENT = 'ON_READ_ANOUNCEMENT'

//Live
export const INITIATE_LIVE_STREAMING = 'INITIATE_LIVE_STREAMING';
export const SET_LIVE_ID = 'SET_LIVE_ID';
export const SET_STREAMING_ID = 'SET_STREAMING_ID';
export const CREATE_LIVE_PROFILE = 'CREATE_LIVE_PROFILE';
export const ADD_LIVE_LISTENER = 'ADD_LIVE_LISTENER';
export const SEND_COMMENTS = 'SEND_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_GIFTED_GIFTS = 'SET_GIFTED_GIFTS';
export const ADD_HEART = 'ADD_HEART';
export const REMOVE_HEART = 'REMOVE_HEART';
export const SET_HEARTS = 'SET_HEARTS';
export const SET_EXIT_ALERT_VISIBLE = 'SET_EXIT_ALERT_VISIBLE';
export const SET_IS_LIVE_START = 'SET_IS_LIVE_START';
export const SET_ROOM_USER_COUNT = 'SET_ROOM_USER_COUNT';
export const SET_WAITLIST_DATA = 'SET_WAITLIST_DATA';
export const SET_WAITING_LIST_VISIBLE = 'SET_WAITING_LIST_VISIBLE';
export const SEND_CALL_REQUEST_TO_USER = 'SEND_CALL_REQUEST_TO_USER';
export const SET_LAYOUT = 'SET_LAYOUT'
export const RESET_LIVE_STATE = 'RESET_LIVE_STATE'
export const ON_STREAM_UPDATE = 'ON_STREAM_UPDATE'
export const SET_CO_HOST_DATA = 'SET_CO_HOST_DATA';
export const END_LIVE_CALL = 'END_LIVE_CALL'
export const ON_LIVE_MUTE_UNMUTE = 'ON_LIVE_MUTE_UNMUTE'
export const SET_LIVE_IS_MUTE = 'SET_LIVE_IS_MUTE'
export const ON_APP_STATE_CHANGE_IN_LIVE = 'ON_APP_STATE_CHANGE_IN_LIVE'

//Chat
export const ON_ACCEPT_REJECT_CHAT = 'ON_ACCEPT_REJECT_CHAT'
export const SET_CHAT_TIMER_COUNTDOWN = 'SET_CHAT_TIMER_COUNTDOWN'
export const SET_CHAT_DATA = 'SET_CHAT_DATA'
export const SET_CHAT_REQUESTED_DATA = 'SET_CHAT_REQUESTED_DATA'
export const ON_INITIATE_CHAT = 'ON_INITIATE_CHAT'
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE'
export const SAVE_CHAT_MESSAGE = 'SAVE_CHAT_MESSAGE'
export const ON_END_CHAT = 'ON_END_CHAT'
export const ON_CLOSE_CHAT = 'ON_CLOSE_CHAT'
export const ON_CHAT_IMAGE_SEND = 'ON_CHAT_IMAGE_SEND'
export const SET_CHAT_IMAGE_DATA = 'SET_CHAT_IMAGE_DATA'
export const GET_INTAKE_DETAILS = 'GET_INTAKE_DETAILS'
export const SET_LINKED_PROFILE_DATA = 'SET_LINKED_PROFILE_DATA'

export const SET_CALL_REQUEST_DATA = 'SET_CALL_REQUEST_DATA'
export const SET_CALL_VIDEO_REQUREST_DATA = 'SET_CALL_VIDEO_REQUREST_DATA'

export const GET_CHAT_HISTORY = 'GET_CHAT_HISTORY'
export const SET_CHAT_HISTORY = 'SET_CHAT_HISTORY'
export const GET_CALL_HISTORY = 'GET_CALL_HISTORY'
export const SET_CALL_HISTORY = 'SET_CALL_HISTORY'
export const GET_LIVE_VEDIO_CALL_HISTORY = 'GET_LIVE_VEDIO_CALL_HISTORY'
export const SET_LIVE_VEDIO_CALL_HISTORY = 'SET_LIVE_VEDIO_CALL_HISTORY'
export const GET_WALLET_HISTORY = 'GET_WALLET_HISTORY';
export const SET_WALLET_HISTORY = 'SET_WALLET_HISTORY';
export const GET_VIDEO_CALL_HISTORY = 'GET_VIDEO_CALL_HISTORY'
export const SET_VIDEO_CALL_HISTORY = 'SET_VIDEO_CALL_HISTORY'
export const GET_GIFT_ORDER_HISTORY = 'GET_GIFT_ORDER_HISTORY'
export const GET_STATUS_ONLINE = 'GET_STATUS_ONLINE'
export const SET_GIFT_ORDER_HISTORY = 'SET_GIFT_ORDER_HISTORY'

//Kundli
//Kundli
export const SET_KUNDLI_PAYLOADS = 'SET_KUNDLI_PAYLOADS'
export const RESET_KUNDLI_DATA = 'RESET_KUNDLI_DATA'
export const CREATE_KUNDLI = 'CREATE_KUNDLI'
export const GET_ALL_KUNDLI = 'GET_ALL_KUNDLI'
export const SET_ALL_KUNDLI = 'SET_ALL_KUNDLI'
export const SET_ALL_MASTRER_KUNDLI = 'SET_ALL_MASTRER_KUNDLI'
export const DELETE_KUNDLI = 'DELETE_KUNDLI'
export const GET_KUNDLI_DATA = 'GET_KUNDLI_DATA'
export const SET_KUNDLI_ID = 'SET_KUNDLI_ID'
export const GET_KUNDLI_BIRTH_DETAILS = 'GET_KUNDLI_BIRTH_DETAILS'
export const SET_KUNDLI_BIRTH_DETAILS = 'SET_KUNDLI_BIRTH_DETAILS'
export const GET_KUNDLI_CHART_DATA = 'GET_KUNDLI_CHART_DATA'
export const SET_KUNDLI_CHARTS = 'SET_KUNDLI_CHARTS'
export const SET_KUNDLI_BASIC_DETAILS = 'SET_KUNDLI_BASIC_DETAILS'
export const SET_PLANET_DATA = 'SET_PLANET_DATA'
export const GET_PLANET_DATA = 'GET_PLANET_DATA'
export const SET_KP_PLANET_DATA = 'SET_KP_PLANET_DATA'
export const GET_KP_PLANET_DATA = 'GET_KP_PLANET_DATA'
export const SET_KP_HOUSE_CUPS_DATA = 'SET_KP_HOUSE_CUPS_DATA'
export const GET_KP_HOUSE_CUPS_DATA = 'GET_KP_HOUSE_CUPS_DATA'
export const GET_KUNDLI_MAJOR_DASHA = 'GET_KUNDLI_MAJOR_DASHA'
export const SET_KUNDLI_MAJOR_DASHA = 'SET_KUNDLI_MAJOR_DASHA'
export const GET_KUNDLI_SUB_V_DASHA = 'GET_KUNDLI_SUB_V_DASHA'
export const SET_KUNDLI_SUB_V_DASHA = 'SET_KUNDLI_SUB_V_DASHA'
export const SET_KUNDLI_DAHSA_VISIBLE = 'SET_KUNDLI_DAHSA_VISIBLE'
export const SET_KUNDLI_DASHA_PATH = 'SET_KUNDLI_DASHA_PATH'
export const GET_KUNDLI_SUB_SUB_V_DASHA = 'GET_KUNDLI_SUB_SUB_V_DASHA'
export const SET_KUNDLI_SUB_SUB_V_DASHA = 'SET_KUNDLI_SUB_SUB_V_DASHA'
export const GET_KUNDLI_SUB_SUB_SUB_V_DASHA = 'GET_KUNDLI_SUB_SUB_SUB_V_DASHA'
export const SET_KUNDLI_SUB_SUB_SUB_V_DASHA = 'SET_KUNDLI_SUB_SUB_SUB_V_DASHA'
export const GET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA = 'GET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA'
export const SET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA = 'SET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA'
export const GET_HOUSE_REPORTS = 'GET_HOUSE_REPORTS'
export const SET_HOUSE_REPORTS = 'SET_HOUSE_REPORTS'
export const GET_RASHI_REPORTS = 'GET_RASHI_REPORTS';
export const SET_RASHI_REPORTS = 'SET_RASHI_REPORTS';
export const GET_ASTAK_REPORTS = 'GET_ASTAK_REPORTS';
export const SET_ASTAK_REPORTS = 'SET_ASTAK_REPORTS';
export const GET_SARVA_REPORTS = 'GET_SARVA_REPORTS';
export const SET_SARVA_REPORTS = 'SET_SARVA_REPORTS';
export const GET_ASCEDENT_REPORTS = 'GET_ASCEDENT_REPORTS';
export const SET_ASCEDENT_REPORTS = 'SET_ASCEDENT_REPORTS';
export const GET_BASIC_PANCHANGE = 'GET_BASIC_PANCHANGE';
export const SET_BASIC_PANCHANGE = 'SET_BASIC_PANCHANGE';
export const GET_NUMERO_REPORT = 'GET_NUMERO_REPORT';
export const SET_NUMERO_REPORT = 'SET_NUMERO_REPORT';

export const GET_KUNDLI_D7_CHARTS = "GET_KUNDLI_D7_CHARTS"
export const SET_KUNDLI_D7_CHARTS = "SET_KUNDLI_D7_CHARTS"
export const GET_KUNDLI_D9_CHARTS = "GET_KUNDLI_D9_CHARTS"
export const SET_KUNDLI_D9_CHARTS = "SET_KUNDLI_D9_CHARTS"


export const GET_KUNDLI_MATCHING_REPORT_POINTS = 'GET_KUNDLI_MATCHING_REPORT_POINTS'
export const SET_KUNDLI_MATCHING_REPORT_POINTS = 'SET_KUNDLI_MATCHING_REPORT_POINTS'
export const GET_KUNDLI_MATCHING_DSHKOOT_POINTS = 'GET_KUNDLI_MATCHING_DSHKOOT_POINTS'
export const SET_KUNDLI_MATCHING_DSHKOOT_POINTS = 'SET_KUNDLI_MATCHING_DSHKOOT_POINTS'
export const GET_KUNDLI_MATCHING_CONCLUSION_POINTS = 'GET_KUNDLI_MATCHING_CONCLUSION_POINTS'
export const SET_KUNDLI_MATCHING_CONCLUSION_POINTS = 'SET_KUNDLI_MATCHING_CONCLUSION_POINTS'

//Kundli Matching
export const SET_MALE_KUNDLI_DATA = 'SET_MALE_KUNDLI_DATA'
export const SET_FEMALE_KUNDLI_DATA = 'SET_FEMALE_KUNDLI_DATA'
export const GET_KUNDLI_MATCHING_REPORT = 'GET_KUNDLI_MATCHING_REPORT'
export const GET_KUNDLI_MATCHING_ASHTAKOOT_POINTS = 'GET_KUNDLI_MATCHING_ASHTAKOOT_POINTS'
export const SET_KUNDLI_MATCHING_ASHTAKOOT_POINTS = 'SET_KUNDLI_MATCHING_ASHTAKOOT_POINTS'
export const VIEW_KUNDLI_FROM_KUNDLI_MATCHING = 'VIEW_KUNDLI_FROM_KUNDLI_MATCHING'
export const SET_KUNDLI_BASIC_DETAILS_MATCHING = 'SET_KUNDLI_BASIC_DETAILS_MATCHING'
export const GET_KUNDLI_BASIC_DETAILS_MATCHING = 'GET_KUNDLI_BASIC_DETAILS_MATCHING'
export const SET_BASIC_ASTRO_POINTS = 'SET_BASIC_ASTRO_POINTS'
export const GET_BASIC_ASTRO_POINTS = 'GET_BASIC_ASTRO_POINTS'
export const GET_ASCEDENT_MATCHING_REPORTS = "GET_ASCEDENT_MATCHING_REPORTS"
export const SET_ASCEDENT_MATCHING_REPORTS = 'SET_ASCEDENT_MATCHING_REPORTS'

//Astromall

export const GET_ASTROMALL_DATA = 'GET_ASTROMALL_DATA'
export const SET_ASTROMALL_POOJA_DATA = 'SET_ASTROMALL_POOJA_DATA'
export const SET_ASTROMALL_SPELL_DATA = 'SET_ASTROMALL_SPELL_DATA'
export const REGISTER_POOJA = 'REGISTER_POOJA'
export const GET_REGISTERED_POOJA = 'GET_REGISTERED_POOJA'
export const SET_REGISTERED_POOJA = 'SET_REGISTERED_POOJA'

export const ON_VIDEO_CALL_END = 'ON_VIDEO_CALL_END';

// AstrologerWithdraw  api call
export const GET_WITHDRAW_WALLET = 'GET_WITHDRAW_WALLET';
export const SET_WITHDRAW_WALLET = 'SET_WITHDRAW_WALLET';

// astrowitdrawe amount dqata field

export const AMOUNT_WITHDRAW_DATA = 'AMOUNT_WITHDRAW_DATA';

//Notifications 
export const GET_NOTIFICATIONS_DATA = 'GET_NOTIFICATIONS_DATA ' ;
export const SET_NOTIFICATIONS_DATA = 'SET_NOTIFICATIONS_DATA ' ;

//Assigned Puja
export const GET_ASSIGNEDPUJA_DATA = 'GET_ASSIGNEDPUJA_DATA' ;
export const SET_ASSIGNEDPUJA_DATA = 'SET_ASSIGNEDPUJA_DATA' ;
export const GET_ASSIGNEDPUJA_UPLOAD = 'GET_ASSIGNEDPUJA_UPLOAD';
export const GET_ASTROLOGER_COMPLETE_POOJA = 'GET_ASTROLOGER_COMPLETE_POOJA';
export const SET_ASTROLOGER_COMPLETE_POOJA = 'SET_ASTROLOGER_COMPLETE_POOJA';



// Get Offline & Online Status

export const GET_OFFLINE_DATA = 'GET_OFFLINE_DATA' ;
export const SET_OFFLINE_DATA = 'SET_OFFLINE_DATA' ;

export const GET_ONLINE_DATA = 'GET_ONLINE_DATA' ;
export const SET_ONLINE_DATA = 'SET_ONLINE_DATA' ;